# Generated by Django 3.2.23 on 2024-01-23 13:39

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(default='default_post_orqqen', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('location', models.FloatField(blank=True, null=True)),
                ('event_date', models.DateTimeField()),
                ('event_category', models.CharField(choices=[('games', 'Games'), ('movies', 'Movies'), ('street_art', 'Street art'), ('sport', 'Sport'), ('languages', 'Languages'), ('other', 'Other')], default='other', max_length=32)),
                ('indoor_outdoor', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor')], default='indoor', max_length=15)),
                ('event_registration', models.BooleanField(default=False)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
