# Generated by Django 3.2.23 on 2024-01-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('social_events', '0002_alter_socialevent_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialevent',
            name='tags',
        ),
        migrations.AddField(
            model_name='socialevent',
            name='tags',
            field=models.ManyToManyField(to='tags.Tag'),
        ),
    ]
