# Generated by Django 3.2.23 on 2024-03-08 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_events', '0007_alter_socialevent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialevent',
            name='content',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
