# Generated by Django 3.2.23 on 2024-02-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='../profile_avatar_nxydwh', upload_to='images/'),
        ),
    ]
