# Generated by Django 3.2.23 on 2024-02-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='../avatar_unisex_dj6lm5', upload_to='images/'),
        ),
    ]
