# Generated by Django 3.2.23 on 2024-01-23 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_events', '0001_initial'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialEventComment',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comments.comment')),
                ('social_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_events.socialevent')),
            ],
            options={
                'ordering': ['created_at'],
            },
            bases=('comments.comment',),
        ),
    ]
