# Generated by Django 3.2.23 on 2024-02-22 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_socialeventcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='socialeventcomment',
            options={'ordering': ['-created_at']},
        ),
    ]
