# Generated by Django 3.2.23 on 2024-01-24 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0002_alter_post_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(choices=[('inappropriate', 'Inappropriate content'), ('spam', 'Spam'), ('offensive', 'Offensive content'), ('violence', 'Violent content'), ('sexual', 'Sexual content'), ('unrelated', 'Not related to the neighbourhood'), ('other', 'Other')], max_length=50)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialEventReport',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.report')),
                ('social_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_events.socialevent')),
            ],
            options={
                'ordering': ['created_at'],
            },
            bases=('reports.report',),
        ),
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.report')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
            options={
                'ordering': ['created_at'],
            },
            bases=('reports.report',),
        ),
    ]
