# Generated by Django 3.2.23 on 2024-01-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='flag',
            field=models.CharField(choices=[('inappropriate', 'Inappropriate content'), ('spam', 'Spam'), ('offensive', 'Offensive content'), ('violence', 'Violent content'), ('sexual', 'Sexual content'), ('unrelated', 'Not related to the neighbourhood'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
